
FROM python:3.12-slim


WORKDIR /app


COPY requirements_st.txt .
RUN pip install --no-cache-dir -r requirements_st.txt

COPY streamlit_app.py .
COPY model.py .
COPY models models/

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]